### PR TITLE
Adds pundit to the app

### PR DESCRIPTION
**Pull request by gnardini**
## Summary
Adds Pundit to authorize only certain users to perform certain actions.

**[Trello card](https://trello.com/c/Ugx79vGv/16-instalar-y-configurar-pundit)**

### CODE REVIEW

**Comment by epintos** [comment]
@gnardini What about the views?

**Comment by gnardini** [comment]
What views? Maybe I missed something! All this does is if a user is not authenticated he's redirected to where he came from. Should I do something else?

**Comment by epintos** [comment]
@gnardini In the views you can use pundit when you need to hide a button for example. For example if you want the edit button of an article to be seen by the author, then you can use pundit there

**Comment by gnardini** [comment]
My bad, I missed that part of the docs. Added pundit auth to views :)

**Pull request merged**
